# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RegistroUsuarios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RegistroUsuarios

	pod 'Firebase/Firestore'
	pod 'Firebase/Auth'
	pod 'Firebase/Storage'

  target 'RegistroUsuariosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RegistroUsuariosUITests' do
    # Pods for testing
  end

end
